# Generated by Django 4.1.4 on 2022-12-17 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rutas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shortname', models.CharField(max_length=100)),
                ('fullname', models.TextField(blank=True)),
                ('services', models.CharField(max_length=100)),
                ('schedule', models.IntegerField()),
                ('importantPlaces', models.TextField(blank=True)),
                ('validate', models.CharField(max_length=100)),
                ('score', models.IntegerField(null=True)),
            ],
        ),
    ]
