# Generated by Django 4.1.4 on 2022-12-15 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablaprofile',
            name='url_image',
            field=models.ImageField(blank=True, default='', upload_to='assets/img/'),
        ),
    ]
