# Generated by Django 4.1.4 on 2022-12-17 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('badges', '0001_initial'),
        ('user', '0002_alter_tablaprofile_url_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tablaprofile',
            name='badges',
        ),
        migrations.AddField(
            model_name='tablaprofile',
            name='id_badge',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='badges.badges'),
        ),
        migrations.AlterField(
            model_name='tablaprofile',
            name='url_image',
            field=models.ImageField(blank=True, default='', upload_to='assets/imgProfile/'),
        ),
    ]
