# Generated by Django 4.1.4 on 2022-12-17 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('badges', '0001_initial'),
        ('user', '0003_remove_tablaprofile_badges_tablaprofile_id_badge_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablaprofile',
            name='id_badge',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='badges.badges'),
        ),
    ]
