# Generated by Django 4.1.4 on 2022-12-17 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Badges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('experience', models.FloatField()),
                ('photo', models.ImageField(blank=True, default='', upload_to='assets/resources/')),
            ],
        ),
    ]
